### ISSUE TITLE
T5 load error

### ISSUE THREAD

**Issue by gassannov** [feizc/FluxMusic#18]
get this error:
Traceback (most recent call last):
  File "/workspace/disk1/gasanov/FluxMusic/sample.py", line 119, in <module>
    main(args)
  File "/workspace/disk1/gasanov/FluxMusic/sample.py", line 64, in main
    t5 = load_t5(device, max_length=256)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/disk1/gasanov/FluxMusic/utils.py", line 9, in load_t5
    return HFEmbedder("google/t5-v1_1-xxl", max_length=max_length, torch_dtype=torch.bfloat16).to(device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/disk1/gasanov/FluxMusic/modules/conditioner.py", line 25, in __init__
    self.tokenizer: T5Tokenizer = T5Tokenizer.from_pretrained(local_path_tokenizer, max_length=max_length)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2190, in from_pretrained
    resolved_config_file = cached_file(
                           ^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/transformers/utils/hub.py", line 466, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: '/maindata/data/shared/multimodal/public/ckpts/stable-diffusion-3-medium-diffusers/tokenizer_3'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

when running:
python sample.py \
--version base \
--ckpt_path checkpoints/flux-music-base.pt \
--prompt_file config/example.txt

**Comment by Skquark** [comment]
I'm getting the exact same error here using same code as examples, and trying to figure out fix. Trace it back to figure out if there's anything we can do, and see in modules/conditioner.py the path is hard coded to an incorrect local directory.  When I looked at the same code in the curtified/FluxMusicGUI repo I see that it's using the correct HuggingFace model ID there instead.  Looks like an easy update....

**Comment by eftSharptooth** [comment]
Yes, this repo has the models currently hardcoded. You can modify the paths yourself, or use the repo that has added the download as mentioned above.

**Comment by DarkAlchy** [comment]
which repo because the gui has way more issues than this does at the moment?  Both devs seems to have dump and run, tbf.
