### ISSUE TITLE
'0050000.pt' not found

### ISSUE THREAD

**Issue by pbz134** [feizc/FluxMusic#8]
Hello,

I am currently installing your program in a Conda environment. After getting all the packages, I get the following error:

Traceback (most recent call last):
  File "F:\FluxMusic\sample.py", line 120, in <module>
    main(args)
  File "F:\FluxMusic\sample.py", line 58, in main
    state_dict = torch.load(local_path, map_location=lambda storage, loc: storage)
  File "D:\Programme\Miniconda3\envs\FluxMusic\lib\site-packages\torch\serialization.py", line 1065, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "D:\Programme\Miniconda3\envs\FluxMusic\lib\site-packages\torch\serialization.py", line 468, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "D:\Programme\Miniconda3\envs\FluxMusic\lib\site-packages\torch\serialization.py", line 449, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/maindata/data/shared/multimodal/zhengcong.fei/code/music-flow/results/base/checkpoints/0050000.pt'

How can I get this file?

**Comment by abh1nash** [comment]
There's a fork that replaces the hardcoded model paths. You can try that one: https://github.com/feizc/FluxMusic/issues/3#issuecomment-2330249398

**Comment by feizc** [comment]
Hi, we have cleaned the sample.py code with args instead of local path :)
